### ISSUE TITLE
Getting "The geopip is not valid" often

### ISSUE THREAD

**Issue by fromagnoli11** [awssat/laravel-visits#11]
I have a Partner Model. Every Partner has it's own page. 

Within my e.g. PartnerController, I would do this:

```
public function getProfile($username){
	$partner = Partner::where('username', $username)->first();  
    	$partner->visits()->increment();
    	$partner->visits()->count(); 

return view('partner.profile.show', compact('partner'));
}
```

Partner.php

```
 public function visits()
    {
        return visits($this);
    }
```

But somehow, I get the exception "The geoip is not valid", way too often? After clearing cache and config, it still returns the exception, multiple times...

Any way around the geoip?

By the way, thank you for the great logic, and package.

**Comment by if4lcon** [comment]
https://github.com/awssat/laravel-visits/issues/8

Thanks for your kind words .

**Comment by if4lcon** [comment]
#8

**Comment by if4lcon** [comment]
Also you should get geiop config : 
`php artisan vendor:publish --provider="Torann\GeoIP\GeoIPServiceProvider" --tag=config`

**Comment by fromagnoli11** [comment]
After publishing the geoip config, I get: This cache store does not support tagging.

**Comment by if4lcon** [comment]
see https://github.com/Torann/laravel-geoip
