### ISSUE TITLE
Not working with with laravel 5.7

### ISSUE THREAD

**Issue by infinitypaul** [awssat/laravel-visits#12]
<img width="571" alt="screen shot 2018-09-05 at 10 13 43 pm" src="https://user-images.githubusercontent.com/15332137/45121444-122dd780-b159-11e8-8b81-9ecf508a9b22.png">

i recently updated my laravel to 5.7... i am getting the above error why installing your package

**Comment by if4lcon** [comment]
Done . https://github.com/awssat/laravel-visits/commit/7cfbaefdfd681394c08edf6b25ed47b2c7d205ab
