### ISSUE TITLE
Incorrect daily visit count 

### ISSUE THREAD

**Issue by SPQRInc** [awssat/laravel-visits#18]
Hello,

I created these two calls to `visit`:

```
 $user_visits       = visits('App\User')->count();
 $user_visits_today = visits('App\User')->period('day')->count();
```

`$user_visits` is always correct, I am often getting this result:

- `$user_visits`: 13
- `$user_visits_today`: 0

After visiting a user's profile, which calls `$user->visits()->seconds(86400)->increment();`, the result is:

- `$user_visits`: 14
- `$user_visits_today`:  14

**Comment by if4lcon** [comment]
Your version ?

**Comment by SPQRInc** [comment]
`composer show`

```
awssat/laravel-visits                 1.4.4    Laravel Redis visits counter for Eloquent models
```

**Comment by if4lcon** [comment]
if you call `visits($user)->period('day')->count();` is it correct ?

**Comment by if4lcon** [comment]
can you please update and see if this resolves your issue

**Comment by if4lcon** [comment]
strange .. can you confirm it on redis editor like https://tableplus.io/ or https://github.com/erikdubbelboer/phpRedisAdmin  ?

if you know redis commands you can log into console and find day value and ttl

**Comment by if4lcon** [comment]
I'm not able to reproduce this issue .. I've created tests and test it on my website seems works fine

**Comment by SPQRInc** [comment]
I will double-check it in a few hours (I'm currently on my mobile device)... :-) I'll try to provide as much information as possible.

**Comment by SPQRInc** [comment]
Hmm.. What value do I have to check?

```
ZSET: visits:users_visits_day
```

has the content

`0`

The value

```
visits:users_visits_day_total
```

has the value 1.

But on my view the result of 

```
visits('App\User')->period('day')->count();
```

is still `15`.

**Comment by if4lcon** [comment]
`visits:users_visits_day_total` = `visits('App\User')->period('day')->count();`
 
edit `count` method on vendor/awssat/laravel-visits/visits.php 

before line 126 add  : 

```php
dd($this->keys->visitsTotal());
```

and paste the dump key here

**Comment by if4lcon** [comment]
Are sure you are executing ‘visits('App\User')->period('day')->count();’ only ?

**Comment by SPQRInc** [comment]
Hi,

this is the full source of the controller's `index` method:

```
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Carbon\Carbon;

class HomeController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        view()->share('siteTitle', '...');
        view()->share('siteDescription',
            '...');
        view()->share('siteKeywords',
            '...');
    
        $users = User::currentStatus('published')->where([
            [
                'registered_on',
                '<',
                Carbon::now()->toDateTimeString(),
            ]
        ])->count();
        
        $users_today = User::currentStatus('published')->where([
            [
                'registered_on',
                '>=',
                Carbon::today(),
            ],
        ])->count();
        
        $user_visits       = visits('App\User')->count();
        $user_visits_today = visits('App\User')->period('day')->count();
    
        return view('home.index',
            compact('users', 'users_today', 'user_visits',
                'user_visits_today'));
    }
}
```

**Comment by if4lcon** [comment]
just comment this line and execute your route

`//$user_visits       = visits('App\User')->count();`

**Comment by if4lcon** [comment]
after finish this ... revert vendor/awssat/laravel-visits/visits.php

then in routes/web.php add new route to debug : 
```php
Route::get('debug-laravel-visits', function() { 
        $user_visits       = visits('App\User')->count();
        $user_visits_today = visits('App\User')->period('day')->count();

return compact('user_visits', 'user_visits_today');
});
```

visit that route `debug-laravel-visits` and paste output here

**Comment by SPQRInc** [comment]
Hm...

```
{"user_visits":17,"user_visits_today":2}
```

This is correct. But why is it different later in my view? Maybe there's a caching-problem somewhere... I am using OPCache with PHP.

I will check that out. Thanks so far for your great help! I highly appreciate it.

**Comment by if4lcon** [comment]
I think you are overwriting $user_visits_today somewhere in your view ... thanks for your help making the package better
