### ISSUE TITLE
laravel 5.7 install error

### ISSUE THREAD

**Issue by sweida** [awssat/laravel-visits#19]
composer require awssat/laravel-visits
error:
```
In VisitsServiceProvider.php line 21:

  Call to undefined method Carbon\Carbon::macro()

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```
![_20190218195311](https://user-images.githubusercontent.com/23181508/52949280-cbeecc80-33b6-11e9-90be-144297ad85f4.png)

**Comment by if4lcon** [comment]
do you have Carbon dependency ?

**Comment by if4lcon** [comment]
I have released new version update and see if it resolve your issue

**Comment by sweida** [comment]
resolved，thanks !!
