### ISSUE TITLE
Save it into Mysql?

### ISSUE THREAD

**Issue by fhferreira** [awssat/laravel-visits#2]
I would like if do you have plans to put it into a database?

**Comment by if4lcon** [comment]
Redis used often as fast-database and it's good for counters

**Comment by fhferreira** [comment]
I am asking because sometimes when we restart redis we lost the data. Thank you for your fast reply.

**Comment by if4lcon** [comment]
you can make a job that handle the backup process of your Redis storage

**Comment by fhferreira** [comment]
Yes, I think I will be do something like that, but in the future. Now we will start to use the package first.

**Comment by ctf0** [comment]
@if4lcon maybe we can add a wiki for user on how to implement this feature ?

**Comment by if4lcon** [comment]
@ctf0 Simple job running every hour to backup redis storage . store it somewhere “mysql, cache” and if redis failed .. get your data from the backup .. even better solution  configure redis to save all data on the disk
