### ISSUE TITLE
[Proposal] More granularity in configuration/helper

### ISSUE THREAD

**Issue by CDNRocket** [awssat/laravel-visits#22]
Should be good to have more options in the config/helper, for example for choosing what values we need and optimize ram usage, that is a precious resource.

For example, when we need to save only total views of a specific model (and show it in the page as a counter) and not countries, ip, day/month/years, etc.
Because very often we manage these data through log analysis (or other analytics) and these will be a duplication and a waste of resources.

What do you'all think?

**Comment by if4lcon** [comment]
feel free to post a PR with test for this I would be happy to merge it

**Comment by abdumu** [comment]
> options in the config/helper, for example for choosing what values we need 

Since PR #25 is introducing ignore ability to specific items (countries etc)  as a parameter, we might be able to add a global `ignore` to config file ..
