### ISSUE TITLE
Connection refused [tcp://127.0.0.1:6379] during test

### ISSUE THREAD

**Issue by ludo237** [awssat/laravel-visits#23]
## Detailed description

As it turns out this package rely heavily on Redis, which is fine, but there's a problem if you try to test an HTTP layer for example

## Context

HTTP and Unit tests on models that have visit package integrated

How can it benefit other users?

## Possible implementation

/

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 5.6, HHVM 3): 7.3
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Xenial

**Comment by ludo237** [comment]
Ok it's impossible to mock this library, you have to have Redis in your CI environment

**Comment by if4lcon** [comment]
Mocking is not real testing .. but we can do it (With some changes) you could create an interface one for fake and second for redis .. if you want to invest your time on that I'll be happy to help. feel free to open a new PR

**Comment by ludo237** [comment]
The point is that I did not want to test the library per se, hence the mocking, I did want to test an HTTP endpoint that provides the user data, with also the visits count.

I would definitely dig into that more as soon as possible, but for now for everybody that uses this package with a CI they should attach a Redis service and connect it.
