### ISSUE TITLE
laravel5.8, the count always 0

### ISSUE THREAD

**Issue by sweida** [awssat/laravel-visits#24]
laravel5.8 project
use 
```php
$article = Article::find(1);

visits($article)->increment();

$article->view_count = visits($article)->count();
```

but the count always 0

<img width="420" alt="WX20190518-145431@2x" src="https://user-images.githubusercontent.com/23181508/57965892-1fa09000-797d-11e9-804c-7eeccae3a039.png">

thank you very much!!!

**Comment by if4lcon** [comment]
`dd(visits($article)->count());`

**Comment by if4lcon** [comment]
see https://github.com/awssat/laravel-visits/issues/18

**Comment by sweida** [comment]
fixed the problem, the Postman have to set Header 'User-Agent:Mozilla/5.0 (Macintosh;......', the count can add. But the other problem, every time add count, throw out this error
![image](https://user-images.githubusercontent.com/23181508/57995567-61ecdd00-7af5-11e9-840c-2bd8931fc1da.png)
why?
