### ISSUE TITLE
Please update for laravel 6.x

### ISSUE THREAD

**Issue by nphuy** [awssat/laravel-visits#26]
Please update for laravel 6.x

**Comment by abdumu** [comment]
@nphuy the current code in master repo is the candidate of the version 2.0. 
you can start using it and test it if you are in a hurry ..

**Comment by nphuy** [comment]
@abdumu I encountered an error **Call to undefined function awssat\Visits\Traits\studly_case()**
But do not know how to fix the error

**Comment by abdumu** [comment]
@nphuy it's fixed now

**Comment by nphuy** [comment]
@abdumu Thank you, It was working again
