### ISSUE TITLE
visits($model)->increment(1); returns null;

### ISSUE THREAD

**Issue by PR4M** [awssat/laravel-visits#36]
I'm using Laravel 6.x and Laravel Visits ^2.0,

in my TutorialController, I've these following codes:

```php
 $check = visits($tutorial)->increment(1, true);
 dd($check);exit;
```

When I access it on a browser, it returns null; When I check the phpRedisAdmin is nothing from Laravel Visits being added. 

my database.php

```php
'redis' => [
    // another redis config
    # For Laravel Visits
        'laravel-visits' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 4, // anything from 1 to 15, except 0 (or what is set in default)
        ],
]
```

Note: _I've already setup the Redis and it's working fine_

Thanks

**Comment by if4lcon** [comment]
Can you check 

https://github.com/awssat/laravel-visits/issues/24

and

https://github.com/awssat/laravel-visits/issues/18

check your browser user-agent , try forceIncrement
