### ISSUE TITLE
This cache store does not support tagging

### ISSUE THREAD

**Issue by mohamedsabil83** [awssat/laravel-visits#37]
- Operating system and version (Ubuntu 19.10):
- Package Version:^2.1-dev
- Laravel Version: 6.9.0
- Link to your project: Local

### Description:
I want to use the database, so, I change the config file to:

> 'engine' => 'eloquent',
> 'connection' => 'mysql',

then when use `visits($blog)->increment()` it's return error message **This cache store does not support tagging**

How to stop tagging in the package?

**Comment by if4lcon** [comment]
https://github.com/awssat/laravel-visits/issues/16
