### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by rlidev** [awssat/laravel-visits#38]
- Operating system and version (Windows 10):
- Package Version: 2.0.0
- Laravel Version: 6.10.0
- Link to your project:

### Description:

Hello, installing the Laravel package and following the installation instructions, this command gives me an error.

php artisan vendor:publish --provider="Awssat\Visits\VisitsServiceProvider" --tag="migrations"

Unable to locate publishable resources.
Publishing complete.

### Steps To Reproduce:

1 - composer require awssat/laravel-visits
2 - php artisan vendor:publish --provider="Awssat\Visits\VisitsServiceProvider" --tag="migrations"

**Comment by if4lcon** [comment]
can you update and check we forget to push new release sorry

**Comment by if4lcon** [comment]
also if you planning to use redis you don't need migrations

**Comment by abdumu** [comment]
@if4lcon is this a bug of 2.1 ? 
If it's 2.0 then it's not a bug.

**Comment by rlidev** [comment]
It was with 2.0.0, anyway as @if4lcon says I don't need to do any migration, since I use Redis. Everything is working perfectly for now.

One tip is that you study how to use Redis from the Laravel docs: [](https://laravel.com/docs/6.x/redis)

Thank you
