### ISSUE TITLE
Tag is always empty, default or optional tags not stored into db

### ISSUE THREAD

**Issue by kevin93d** [awssat/laravel-visits#4]
Hello, I was testing the tag feature on my project, and then I found out that tags are actually not stored into the rdb. And I spent sometime reviewing the source codes and couldn't find out what exactly causes this issue.

This is how I tested the tag feature:
```php
visits($artist, 'test')->increment();
return response(visits($artist, 'test')->count());
```
And this is what actually stored in db:

<img width="347" alt="screen shot 2018-07-26 at 12 40 43 pm" src="https://user-images.githubusercontent.com/11542784/43275915-268fd03c-90d1-11e8-9898-520e3cd88410.png">

When I modified the visits method in Keys class:
```php
     /**
     * Get cache key
     *
     * @param $key
     * @return string
     */
    public function visits($key)
    {
        return "{$this->prefix}:$this->testing" .
            strtolower(str_plural(class_basename(is_string($key) ? $key : get_class($key))))
            . "_test";
    }
```
It does store correctly in db:

<img width="323" alt="screen shot 2018-07-26 at 12 53 39 pm" src="https://user-images.githubusercontent.com/11542784/43276560-09a4a0cc-90d3-11e8-8f1c-4f742b9eb323.png">

---

**I did try to modify the tag value in the constructor or assign a value for the declared parameter, but the actually key store into db is still empty.**

**Comment by if4lcon** [comment]
Thanks for reporting . now fixed

**Comment by kevin93d** [comment]
Thanks for your hard work! 🎉
