### ISSUE TITLE
Eager load relationship for visits

### ISSUE THREAD

**Issue by cioraneanu** [awssat/laravel-visits#41]
I have just started playing with the library so maybe I am missing something obvious, but I couldn't find a way to show visits data for a list of items, without getting into the N+1 problem.

```
$posts = Post::where('isDraft', false)->get();
foreach ($posts as $post) {
    visits($post)->count();
}
```

**Comment by if4lcon** [comment]
what type of data engine for laravel-visits are you using redis or mysql ?

**Comment by cioraneanu** [comment]
Postgres database.

**Comment by abdumu** [comment]
This is supposed to be fixed in the next release and if you want to know how to use it when released, read this part of the docs: 

https://awssat.com/opensource/laravel-visits/4_quick-start.html#integration-with-any-model

thanks.
