### ISSUE TITLE
Laravel Nova Issue

### ISSUE THREAD

**Issue by chrismackie28** [awssat/laravel-visits#43]
- Operating system and version (e.g. Ubuntu 16.04, Windows 7):
MacOS Catalina - Valet

- Package Version: #.#.#
2.2
- Laravel Version: #.#.#
Laravel - 6.2
Nova - 2.11.1
- Link to your project:
N/A
### Description:
I need the ability to ignore this when using Nova as its trying to insert into action_events while editing rows.

### Steps To Reproduce:
Install Laravel + Nova
Create resources
Try to update rows

**Comment by abdumu** [comment]
I tried to reproduce the error but nothing happened. It works and nothing happened to the action events table.

If this is due to the error in bug #44, then it's supposed to be fixed as mentioned in that issue.

thanks.
