### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry 'visits:posts_visits_countries:296-in' for key 'visits.visits_primary_key_secondary_key_unique' 

### ISSUE THREAD

**Issue by deveti** [awssat/laravel-visits#45]
- Operating system and version: Ubuntu 18.04.4 LTS
- Package Version: 2.2.0
- Laravel Version: 6.0.3
- Link to your project: https://izklop.com/

### Description:

I keep getting Duplicate entry errors in my project after deploying to production.

`
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'visits:posts_visits_countries:296-in' for key 'visits.visits_primary_key_secondary_key_unique'
`

`
Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'visits:posts_visits_countries:296-in' for key 'visits.visits_primary_key_secondary_key_unique'
`

`
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'visits:posts_visits_countries:296-in' for key 'visits.visits_primary_key_secondary_key_unique' (SQL: insert into `visits` (`primary_key`, `secondary_key`, `score`, `updated_at`, `created_at`) values (visits:posts_visits_countries:296, in, 1, 2020-03-06 22:14:58, 2020-03-06 22:14:58))
`

### Steps To Reproduce:
`
$post->visits()->increment();
`

**Comment by abdumu** [comment]
Hello, 

Are you using MySQL ?

**Comment by deveti** [comment]
Yes. Sorry for late reply I had disabled notifications.

**Comment by abdumu** [comment]
This is supposed to fixed in the upcoming release. If not, then you can re-open this issue again.

thanks
