### ISSUE TITLE
Redis::zRevRange() expects parameter 4 to be bool, array given on top() or low() methods

### ISSUE THREAD

**Issue by Shocky92** [awssat/laravel-visits#47]
- Operating system and version: Debian GNU/Linux 9 (stretch)
- Package Version: 2.1.2
- Laravel Version: 7.1.3
- Redis Version: 5.0

### Description:
Whenever I call top() or low() command package throws this error.

### Steps To Reproduce:
- install laravel, predis, laravel-visits
- try to get top() or low() visits on model

**Comment by abdumu** [comment]
If you have the ability to try PHPredis instead of predis, will this issue disappear or keep happening ?

https://laravel.com/docs/7.x/redis#phpredis

**Comment by Shocky92** [comment]
Oh sorry, I've mistaken. That error actually happened with PHPredis.
But If I use predis I get this error:
`WRONGTYPE Operation against a key holding the wrong kind of value`
