### ISSUE TITLE
Can statistics be obtained by date?

### ISSUE THREAD

**Issue by myixyt** [awssat/laravel-visits#48]
## Detailed description

Can statistics be obtained by date?For example,I want to get the number of current entries by setting a date。

## Possible implementation

This requirement is used to solve detailed data statistics problems

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 5.6, HHVM 3):
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:
* ...
* ...

**Comment by abdumu** [comment]
can you elaborate ? 

Do you mean by a period like a day or a week. or a real date like 3-4-2019

if it's the first then read here:
https://awssat.com/opensource/laravel-visits/6_retrieve-visits-and-stats.html#an-item-visits

if it's the later then we might add it in a next version.

thanks
