### ISSUE TITLE
Clear cache will clear everything out

### ISSUE THREAD

**Issue by summerblue** [awssat/laravel-visits#5]
## Detailed description

Artisan command line `artisan cache:clear` will clear all the data. This kind of storage should be a persistent storage, not like cache.

## Context

1. Install and used;
2. Set your default cache driver to `redis` at the `config/cache.php` file.
3. Use `artisan cache:clear`;
4. check the `count`;

## Possible implementation

With reference to `connection` field in the `config/session.php` file.

## Your environment

Newly homestead.

**Comment by if4lcon** [comment]
I'm sorry but this not possible we are using redis and `artisan cache:clear` doesn't clear your redis storage

**Comment by summerblue** [comment]
@if4lcon Sorry, there is something I miss, u have to set your default cache driver to `redis` at the `config/cache.php` file.

**Comment by summerblue** [comment]
@abdumu That would be wonderful!

**Comment by if4lcon** [comment]
@summerblue can you try this commit and confirm if is resolve this issue ?

**Comment by summerblue** [comment]
@if4lcon Tested, works perfect. I also put two comments in the commit https://github.com/awssat/laravel-visits/commit/d7ff826f58011dfd0549f087f6ad157034b51705 u should see it, and please put out a new release when u are done. I am waiting for the new release to fix the production code. Thanks a lot.

**Comment by if4lcon** [comment]
@summerblue awesome, Thanks ! .. I have made a few more changes.. check the latest commits ..

can you please try the updated version ?

**Comment by summerblue** [comment]
There're not https://github.com/awssat/laravel-visits/blob/master/composer.json#L19 , refer to this: https://github.com/spatie/laravel-referer/releases

**Comment by adriaanzon** [comment]
I wonder if it should still be documented this way at https://awssat.com/opensource/laravel-visits/3_installation.html#redis-configuration, because [this PR](https://github.com/laravel/laravel/pull/4665) introduced a separate Redis database to store cache items by default.

**Comment by abdumu** [comment]
@adriaanzon good catch. but still for me I think the documentation should stay as a warning because default Redis database still get flushed sometimes. and we should introduce a change like:
```diff
- database => 3,
+ database => env('REDIS_DB', 3),

```
