### ISSUE TITLE
Filtering on Top/Lowest visited items per model

### ISSUE THREAD

**Issue by shingsoso** [awssat/laravel-visits#50]
This is an amazing package , love it ! 
Is there any way for us to do filtering first before getting top 10 visited items by models ?  
Because in many of the use case , we have to retrieve top 10 visited items by the attributes of models .

**Comment by abdumu** [comment]
Please elaborate. Add code example of the idea you are suggesting so we may add it to the next version. 

thanks

**Comment by abdumu** [comment]
Added to latest version. Read the docs for more information
https://github.com/awssat/website/blob/master/opensource/laravel-visits/7_visits-lists.md
