### ISSUE TITLE
Count returns empty array

### ISSUE THREAD

**Issue by gaiahub** [awssat/laravel-visits#55]
When calling count, ` $aa = visits($post)->top(10);
    print_r($aa); die();`, im getting `Illuminate\Support\Collection Object ( [items:protected] => Array ( ) ) `.  But inside `visits` table I see 98 rows of data.

**Comment by abdumu** [comment]
If you are using database engine (not redis) make sure to follow this:


https://awssat.com/opensource/laravel-visits/4_quick-start.html#integration-with-any-model
