### ISSUE TITLE
same value for day, month, year visitor counter

### ISSUE THREAD

**Issue by muaz234** [awssat/laravel-visits#56]
## Problem
I am facing a problem, using `visits('App\Registration')->period('day')->count()` in my view results to same number with `visits('App\Registration')->period('month')->count()` and year `visits('App\Registration')->period('year')->count()`

Don't know why it is behaving as such, mostly I refer to the docs and I only found a solution to reset the counter. 

## Server and Application Environment
- Laravel 7
- PHP 7.2
- Apache Web Server
- MySQL database engine

Hope this give you clear view of my problem and anyone could advice for solution pertaining to the issue. Thanks

**Comment by abdumu** [comment]
Thanks for reporting this issue.
did you add this:

https://awssat.com/opensource/laravel-visits/4_quick-start.html#integration-with-any-model
