### ISSUE TITLE
Question:  count grouped by week/month/year

### ISSUE THREAD

**Issue by kamekun** [awssat/laravel-visits#57]
- Package Version: 2.2.1
- Laravel Version: 6.3

### Description:
Sorrry for this dump question, its there a way to bring the results grouped by (Month, Week, Year) or maybe by model.

like:
```
 visits('App\Specialist')->grouped('months')->count();
OR
 visits($post)->grouped('months')->count();
```
```
[
'1' => 15
'2' => 25
'3' => 8
....
'12' =>  5
]
```

**Comment by if4lcon** [comment]
this library doesn't record every detail so it's not possible to get specific day of a month .. I'm planning to develop this feature if I get support
