### ISSUE TITLE
Redis connection [laravel-visits] not configured.

### ISSUE THREAD

**Issue by jeffesonmaia** [awssat/laravel-visits#6]
Hey guys, 

I have this issues Redis connection [laravel-visits] not configured.

Every time when I try to user this plugin.

**Comment by if4lcon** [comment]
To prvent your data loss add a new conection on config/database.php

‘’’
        'laravel-visits' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 3, // anything from 1 to 15, except 0 (or what is set in default)
        ],
’’’

**Comment by jeffesonmaia** [comment]
I already added and it still does not work

**Comment by jeffesonmaia** [comment]
The way I solved this is by undo-ing this.

Delete the cache for config.

It is located in here

bootstrap/cache/config.php
