### ISSUE TITLE
Monthly wise Top visitors & count 

### ISSUE THREAD

**Issue by s-nadesh** [awssat/laravel-visits#60]
- Package Version: ^2.2
- Laravel Version: 7

### Description:
In my project I want to show Top 5 visitors name & count of articles they visit. May I know how do I achieve this. ? I attached image for the reference. 

![top-visitors](https://user-images.githubusercontent.com/8857848/93886387-f7f4d100-fd02-11ea-8d9c-e6cf5af3f8b8.png)

**Comment by if4lcon** [comment]
you asking for a feature here feel free to submit a PR or donate to support our work and we'll be happy to help you with your request

**Comment by s-nadesh** [comment]
@if4lcon Thanks for your response.
