### ISSUE TITLE
Migration Issue with Laravel V8

### ISSUE THREAD

**Issue by cherosoullis** [awssat/laravel-visits#61]
I follow installation instructions with database as data engine.

When I migrate I get the following error:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 byt
es (SQL: alter table `visits` add unique `visits_primary_key_secondary_key_unique`(`primary_key`, `secondary_key
`))

In my AppServiceProvider I have already 
use Illuminate\Support\Facades\Schema;

    public function boot()
    {
      Schema::defaultStringLength(191);
    }

The problem is with the table $table->unique(['primary_key', 'secondary_key']);

If I change to $table->unique('primary_key', 'secondary_key'); then the migration has no problem but is this the correct approach to fix this error?

Thanks in advance

**Comment by abdumu** [comment]
@cherosoullis No this is wrong, second param is meant for naming. 

Can you confirm something for me, change `create_visits_table.php` as below
```diff
-$table->unique(['primary_key', 'secondary_key']);
+$table->unique(['primary_key', 'secondary_key'], 'unique_visit');
```

and tell me if it works or not.

**Comment by cherosoullis** [comment]
I am using utf8mb4 with MySQL v.8.018. I tried also utf8 but still the same error.

**Comment by abdumu** [comment]
do you still have this bug?
