### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by hellosunnyhihi** [awssat/laravel-visits#63]
- Operating system and version (Window 10):
- Package Version: 2.2
- Laravel Version: 7.24
- Link to your project:

### Description:
when I use command  
php artisan vendor:publish --provider="Awssat\Visits\VisitsServiceProvider" --tag=config

The system show error : "Unable to locate publishable resources" and The file config/visits was not create

**Comment by abdumu** [comment]
Is the bug still exist if you do this?
- remove the package using composer command
- reinstall it .

**Comment by abdumu** [comment]
do you still have this bug?
