### ISSUE TITLE
PHP 8 Suppot

### ISSUE THREAD

**Issue by vandadsoft** [awssat/laravel-visits#65]
- Operating system and version: Ubuntu 20.04
- Package Version: 3.0.1
- Laravel Version: 8.16.1

### Description:
 Problem 1
     - awssat/laravel-visits[3.0.0, ..., 3.0.1] require php ^7.3 -> your php version (8.0.0) does not satisfy that requirement.
     - Root composer.json requires awssat/laravel-visits ^3.0 -> satisfiable by awssat/laravel-visits[3.0.0, 3.0.1].

**Comment by MahdiPishguy** [comment]
+1
