### ISSUE TITLE
Store custom data

### ISSUE THREAD

**Issue by jeffesonmaia** [awssat/laravel-visits#7]
I do not know if it already has, but I think it would be interesting to allow us to pass customized data to the viewer.
Ex: visits($model)->custom(['user_id' => 1])->increment()

**Comment by if4lcon** [comment]
I think by custom you mean relationships ?

**Comment by if4lcon** [comment]
new commit is up you can test it 

`composer require awssat/laravel-visits --dev`

I've added by method : 

```php

visits($model)->by($user)->increment();
visits($model)->by($user)->count();

```

also you can do a bleongsTo relation .. but I'm not sure yet about it

```php

visits($model)->creator->increment();
visits($model)->creator->count();

```
