### ISSUE TITLE
redis queued to database store

### ISSUE THREAD

**Issue by jayenne** [awssat/laravel-visits#70]
Hi,
I've set this package up and am no wondering what the pro's and con's of using Redis vs MySQL.

Does/Can Redis persist the data over years and through downtime like a database would?
Does/Can this package use Redis to queue to DB storage at all?

Visitor data needs to be stored quickly (Redis) and kept for the long term (MySQL) so I imaging Queues would be best - how does this package address this?

I'd appreciate any help understanding/reassuring me that this data is safe.

**Comment by jayenne** [comment]
ok, i think i understand this a bit better. I need to think of Redis as a DB by another name. By this I mean, it is persisted to a "drive" (periodically) to maintain persistance. The Redis/DB trade is one where I get a far greater speeds and a "high-loss potential", against far slower speed but also a "low-loss potential".

I think that sums it up.

**Comment by abdumu** [comment]
Hey, 
If you read the TODOs on readme, you will notice 'An export command to save visits of any periods to a table on the database.'. 

I use this package for a personal project and I do the same, I made a custom command to export what I need to database. 
You can do it that, or wait until we add a command to the package to help you with that in the future.
