### ISSUE TITLE
all period show the same result

### ISSUE THREAD

**Issue by ramouspeppy** [awssat/laravel-visits#75]
I want to show a visit by period like this day, this week, this month, this year and all the time.
but the result always show same result even I dont visit my web today.
the result from today is same like yesterday.

`

        $top10      = visits('App\Product','visits')->top(10);

        $allVisit   = visits('App\Product','visits')->count();

        $todayVisit = visits('App\Product','visits')->period('today')->count();

        $weekVisit  = visits('App\Product','visits')->period('week')->count();

        $monthVisit = visits('App\Product','visits')->period('month')->count();

        $yearVisit  = visits('App\Product','visits')->period('year')->count();
` 

DATE	VIEW
Today	14 -> I dont visit today, this supposed 0,
This Week	14
This Month	14
This Year	14
All The Time	14

**Comment by abdumu** [comment]
@if4lcon this is needed to be investigated before releasing any version of the package. I'll try for now, and see if I can reproduce it ...

**Comment by abdumu** [comment]
@ramouspeppy 

this 
```
    $todayVisit = visits('App\Product','visits')->period('today')->count();
```
should be 'day' instead of 'today' ... we will add an exception to throw if you use a period that is not set in config/visits[periods] key in your config.


I hope this fixes it for you. 

enjoy.
