### ISSUE TITLE
Compatibiltiy with mongodb

### ISSUE THREAD

**Issue by mahmudz** [awssat/laravel-visits#84]
- Windows 10
- Package Version: 3.0
- Laravel Version: 9.2

### Description:
Is this project compatible with MongoDB. While using this package with [laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) package, it throws this exception.

> Call to a member function prepare() on null

As the requirement for using a model with MongoDB, I need to extend the model with jenssegers eloquent model, but as its inside the vendor, & there's no known way to customize it.

**Comment by if4lcon** [comment]
it shouldn't through error ... also we don't have `prepare` method anywhere in our codebase , you can make new data engines as customization ... but I think current db engines are more than enough

**Comment by if4lcon** [comment]
just published new version so you can expand db engine more easily and set your class to visits config.. Happy coding
