### ISSUE TITLE
How can I delete that redis record after deleting the post?

### ISSUE THREAD

**Issue by rlidev** [awssat/laravel-visits#85]
After deleting a post, Visits Lists does not refresh and instead of showing the Top 5 it only shows 4. How can I delete that redis record after deleting the post?

**Comment by abdumu** [comment]
you can do it by reseting. 

https://github.com/awssat/laravel-visits/blob/master/docs/8_clear-and-reset-values.md

if you have a model just use boot functon like this with reset that mentioned above 

```
    protected static function boot()
    {
        parent::boot();

        static::deleting(function ($model) {
            //here
        });

    }
```
