### ISSUE TITLE
Target class [eloquent] does not exist. 

### ISSUE THREAD

**Issue by jarwonozt** [awssat/laravel-visits#95]
I try use engine = 'eloquent' but not working in my app
![Screenshot from 2023-07-27 23-21-55](https://github.com/awssat/laravel-visits/assets/67833034/ba901eb4-2983-4acf-9a85-83d5bed47b87)

**Comment by abdumu** [comment]
Hey, 

Could you please provide me with the steps or configuration changes that you made prior to encountering this bug?

**Comment by abdumu** [comment]
also, did you follow this: 

https://github.com/awssat/laravel-visits/blob/master/docs/3_installation.md#engine

> Suported data engines are \Awssat\Visits\DataEngines\RedisEngine::class, and eloquent currently. If you use  \Awssat\Visits\DataEngines\EloquentEngine::class then data will be stored in the default database (MySQL, SQLite or the one you are using)

**Comment by BSN4** [comment]
upgrade to 6.0.0 and use `\Awssat\Visits\DataEngines\EloquentEngine::class` as engine value
