### ISSUE TITLE
How to store redis data in mysql

### ISSUE THREAD

**Issue by vahidalvandi** [awssat/laravel-visits#96]
- Operating system and version (e.g. Ubuntu 16.04, Windows 7):
- Package Version: #.#.#
- Laravel Version: #.#.#
- Link to your project:

### Description:
I want to store redis data in mysql . I want to use driver to decrease mysql connection

**Comment by BSN4** [comment]
I don't understand, you have two database engines ..
```
Supported Engines: \Awssat\Visits\DataEngines\RedisEngine::class, \Awssat\Visits\DataEngines\EloquentEngine::class
```

just use \Awssat\Visits\DataEngines\RedisEngine::class
