### ISSUE TITLE
Call to a member function setPrefix() on null

### ISSUE THREAD

**Issue by kingashok29** [awssat/laravel-visits#97]
Please see the attached Flareapp.io link for more information.
This was working fine until I updated my Laravel Version to 10. x.
[link to flareapp capture](https://flareapp.io/share/Lm8qn21P)

**Comment by abdumu** [comment]
Hey, 
could you provide more information? 
did you modify visits config file ?

**Comment by kingashok29** [comment]
No I did not made any change to visits.php config file. Just upgraded my laravel version from 8 to 10,also all packages to  support laravel 10, everything worked fine but this package was not working and I have attachment full error above. 
- already cleared all views cache. 
- application cache clear as well. 
- config cache and clear command as well

But still facing same issue.

**Comment by BSN4** [comment]
Upgrade your 'visits.php' you can find a copy here
